minimum_pre_commit_version: 2.13.0
repos:
-   repo: https://github.com/python/black
    rev: 21.6b0
    hooks:
    -   id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      additional_dependencies:
        - flake8-absolute-import
        - flake8-black
        - flake8-docstrings
-   repo: https://github.com/PyCQA/isort
    rev: 5.9.2
    hooks:
    -   id: isort